### ISSUE TITLE
1.3.1 does not compile on Unity 2020.3.36f1

### ISSUE THREAD

**Issue by Alexees** [natmlx/NatDevice#26]
The package does not compile:

```
10: [2022-11-29T13:27:17Z - Unity] Library\PackageCache\ai.natml.natdevice@1.3.1\Runtime\Outputs\TextureOutput.cs(112,29): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)
11: [2022-11-29T13:27:27Z - Unity] Library\PackageCache\ai.natml.natdevice@1.3.1\Runtime\Outputs\TextureOutput.cs(112,29): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)
```

Reintialize needs to be replaced with Resize

**Comment by olokobayusuf** [comment]
[NatDevice, along with our other Unity APIs, requires Unity 2021.2+](https://docs.natml.ai/natdevice/prelims/requirements). Unity 2021 is in LTS, and has been for quite some time now.
