### ISSUE TITLE
Compile time error after upgrading to NatDevice 1.3.1

### ISSUE THREAD

**Issue by thesanketkale** [natmlx/NatDevice#20]
After upgrading NatDevice to 1.2.5 from 1.3.1, I am seeing below compile time errors:

> Library\PackageCache\ai.natml.natdevice@1.3.1\Runtime\Outputs\TextureOutput.cs(112,29): error CS1061: 'Texture2D' does not contain a definition for 'Reinitialize' and no accessible extension method 'Reinitialize' accepting a first argument of type 'Texture2D' could be found (are you missing a using directive or an assembly reference?)

I am using Unity version 2021.1.28f1 with Android target platform on a Windows PC.

![image](https://user-images.githubusercontent.com/36810188/200790211-792d1fea-622c-4451-8484-8559619e919f.png)

**Comment by olokobayusuf** [comment]
> I am using Unity version 2021.1.28f1 with Android target platform on a Windows PC.

NatDevice, along with all our other APIs, requires Unity 2021.2+.
