### ISSUE TITLE
Compile time error after upgrading to NatDevice 1.2.3

### ISSUE THREAD

**Issue by thesanketkale** [natmlx/NatDevice#4]
After upgrading NatDevice to 1.2.3 from 1.2.2, I am seeing below compile time errors:

> Library\PackageCache\ai.natml.natdevice@1.2.3\Runtime\CameraImage.cs(128,24): error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'float' and '<null>'
> Library\PackageCache\ai.natml.natdevice@1.2.3\Runtime\CameraImage.cs(139,24): error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'float' and '<null>'

I am using Unity version 2021.1.28f1 with Android target platform.

![image](https://user-images.githubusercontent.com/36810188/186450794-862099a5-697d-43d3-8179-9b81908940af.png)

Below are my player settings:
![image](https://user-images.githubusercontent.com/36810188/186451179-359602d9-2928-4cd5-b623-587db5b3ece9.png)
